
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import java.awt.event.*;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.GregorianCalendar;
/*
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vaibhav
 */
public class Eventsdetails extends javax.swing.JFrame {
 Connection conn=null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form Eventsdetails
     */
    public Eventsdetails() {
        initComponents();
        conn=javaconnect.ConnecrDb();
        Update_table_day1();
        show_times();
    }
    private void Update_table_day1(){
        String sql="select * from Day1events";
        try{
            pst= conn.prepareStatement(sql);            
            rs=pst.executeQuery();
            event_table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
        try{
            rs.close();
            pst.close();
        }
        catch(Exception e){
            
        }
    }
    }
        private void Update_table_day2(){
        String sql="select * from Day2events";
        try{
            pst= conn.prepareStatement(sql);            
            rs=pst.executeQuery();
            event_table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
        try{
            rs.close();
            pst.close();
        }
        catch(Exception e){
            
        }
    }
    }
    private void Update_table_day3(){
        String sql="select * from Day3events";
        try{
            pst= conn.prepareStatement(sql);            
            rs=pst.executeQuery();
            event_table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
        try{
            rs.close();
            pst.close();
        }
        catch(Exception e){
            
        }
    }
    }

    private void Update_table_sort(int x){
        
        String value=Combo_sort.getSelectedItem().toString();
        
        String sql="select * from Day"+x+"events order by ";
        if(value.equals("End Time")){
            sql+="Endtime";
            try{
            pst= conn.prepareStatement(sql);            
            rs=pst.executeQuery();
            event_table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
        try{
            rs.close();
            pst.close();
        }
        catch(Exception e){}
        }   
      }
        else if(value.equals("Seats")){
            sql+="Seats";
            try{
            pst= conn.prepareStatement(sql);            
            rs=pst.executeQuery();
            event_table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
        try{
            rs.close();
            pst.close();
        }
        catch(Exception e){}
        }   
      }
        else if(value.equals("Start Time")){
            sql+="Starttime";
            try{
            pst= conn.prepareStatement(sql);            
            rs=pst.executeQuery();
            event_table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
        try{
            rs.close();
            pst.close();
        }
        catch(Exception e){}
        }
      }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Combo_sort = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Combo_Day = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        event_table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text_desc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        text_etime = new javax.swing.JTextField();
        text_seats = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        text_name = new javax.swing.JTextField();
        text_time = new javax.swing.JTextField();
        text_venue = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        asas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        datess = new javax.swing.JMenu();
        timess = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Utopia", 3, 24)); // NOI18N
        jLabel1.setText("Sort By:");

        Combo_sort.setBackground(new java.awt.Color(254, 188, 21));
        Combo_sort.setFont(new java.awt.Font("Utopia", 2, 18)); // NOI18N
        Combo_sort.setForeground(new java.awt.Color(255, 255, 0));
        Combo_sort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Start Time", "End Time", "Seats" }));
        Combo_sort.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Combo_sortItemStateChanged(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Utopia", 3, 24)); // NOI18N
        jButton1.setText("Get Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Utopia", 3, 24)); // NOI18N
        jLabel2.setText("Day:");

        Combo_Day.setBackground(new java.awt.Color(247, 255, 0));
        Combo_Day.setFont(new java.awt.Font("Utopia", 2, 18)); // NOI18N
        Combo_Day.setForeground(new java.awt.Color(247, 49, 49));
        Combo_Day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day1", "Day2", "Day3" }));
        Combo_Day.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Combo_DayItemStateChanged(evt);
            }
        });
        Combo_Day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_DayActionPerformed(evt);
            }
        });

        event_table.setBackground(new java.awt.Color(166, 253, 247));
        event_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        event_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        event_table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        event_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                event_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(event_table);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Event Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Utopia", 3, 36), new java.awt.Color(0, 33, 189))); // NOI18N

        jLabel9.setBackground(new java.awt.Color(174, 13, 176));
        jLabel9.setFont(new java.awt.Font("Utopia", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(197, 0, 25));
        jLabel9.setText("Event Name");

        jLabel3.setBackground(new java.awt.Color(174, 13, 176));
        jLabel3.setFont(new java.awt.Font("Utopia", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(197, 0, 25));
        jLabel3.setText("Event ID");

        text_desc.setEditable(false);
        text_desc.setFont(new java.awt.Font("Utopia", 2, 18)); // NOI18N
        text_desc.setForeground(new java.awt.Color(37, 2, 134));
        text_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_descActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(174, 13, 176));
        jLabel7.setFont(new java.awt.Font("Utopia", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(197, 0, 25));
        jLabel7.setText("Description");

        text_etime.setEditable(false);
        text_etime.setFont(new java.awt.Font("Utopia", 2, 18)); // NOI18N
        text_etime.setForeground(new java.awt.Color(37, 2, 134));
        text_etime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_etimeActionPerformed(evt);
            }
        });

        text_seats.setEditable(false);
        text_seats.setFont(new java.awt.Font("Utopia", 2, 18)); // NOI18N
        text_seats.setForeground(new java.awt.Color(37, 2, 134));

        jLabel5.setBackground(new java.awt.Color(174, 13, 176));
        jLabel5.setFont(new java.awt.Font("Utopia", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(197, 0, 25));
        jLabel5.setText("Start Time");

        jLabel6.setBackground(new java.awt.Color(174, 13, 176));
        jLabel6.setFont(new java.awt.Font("Utopia", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(197, 0, 25));
        jLabel6.setText("Venue");

        text_id.setEditable(false);
        text_id.setFont(new java.awt.Font("Utopia", 2, 18)); // NOI18N
        text_id.setForeground(new java.awt.Color(37, 2, 134));
        text_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_idActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(174, 13, 176));
        jLabel8.setFont(new java.awt.Font("Utopia", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(197, 0, 25));
        jLabel8.setText("Seats");

        jLabel4.setBackground(new java.awt.Color(174, 13, 176));
        jLabel4.setFont(new java.awt.Font("Utopia", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(197, 0, 25));
        jLabel4.setText("Start Time");

        text_name.setEditable(false);
        text_name.setFont(new java.awt.Font("Utopia", 2, 18)); // NOI18N
        text_name.setForeground(new java.awt.Color(37, 2, 134));

        text_time.setEditable(false);
        text_time.setFont(new java.awt.Font("Utopia", 2, 18)); // NOI18N
        text_time.setForeground(new java.awt.Color(37, 2, 134));

        text_venue.setEditable(false);
        text_venue.setFont(new java.awt.Font("Utopia", 2, 18)); // NOI18N
        text_venue.setForeground(new java.awt.Color(37, 2, 134));

        jLabel15.setBackground(new java.awt.Color(174, 13, 176));
        jLabel15.setFont(new java.awt.Font("Utopia", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(197, 0, 25));
        jLabel15.setText("Available Seats");

        asas.setEditable(false);
        asas.setFont(new java.awt.Font("Utopia", 2, 18)); // NOI18N
        asas.setForeground(new java.awt.Color(37, 2, 134));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addComponent(text_name, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text_desc)
                    .addComponent(text_seats)
                    .addComponent(text_venue)
                    .addComponent(text_time, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text_etime)
                    .addComponent(asas))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_etime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_venue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_seats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(asas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Lato Semibold", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Event Description");

        jLabel11.setFont(new java.awt.Font("Utopia", 3, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(228, 23, 23));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/balloons.png"))); // NOI18N
        jLabel11.setText("SPRING FEST, IIT KHARAGPUR");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dancing.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/karaoke.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/celebration.png"))); // NOI18N

        jMenu1.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button-Close-icon.png"))); // NOI18N
        jMenuItem2.setText("close");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("                                                                                                                                                                                                                                                                                  ");
        jMenuBar1.add(jMenu2);

        datess.setText("jMenu3");
        jMenuBar1.add(datess);

        timess.setText("jMenu3");
        jMenuBar1.add(timess);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Combo_sort, 0, 140, Short.MAX_VALUE)
                            .addComponent(Combo_Day, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addComponent(jLabel10)
                                .addGap(214, 214, 214))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(342, 342, 342))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel2))
                            .addComponent(Combo_Day, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(Combo_sort, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(59, 59, 59)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(79, 79, 79))))
        );

        setSize(new java.awt.Dimension(1315, 713));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String value=Combo_Day.getSelectedItem().toString();
        if(value.equals("Day1")){
            Update_table_sort(1);
        }
        else if(value.equals("Day2")){
            Update_table_sort(2);
        }
        else if(value.equals("Day3")){
            Update_table_sort(3);
        } else {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Combo_DayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_DayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_DayActionPerformed

    private void Combo_DayItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Combo_DayItemStateChanged
        // TODO add your handling code here:
        String value=Combo_Day.getSelectedItem().toString();
        if(value.equals("Day1")){
            Update_table_day1();
        }
        else if(value.equals("Day2")){
            Update_table_day2();
        }
        else if(value.equals("Day3")){
            Update_table_day3();
        } else {
        }
    }//GEN-LAST:event_Combo_DayItemStateChanged

    private void text_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_idActionPerformed

    private void text_etimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_etimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_etimeActionPerformed

    private void Combo_sortItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Combo_sortItemStateChanged
        // TODO add your handling code here:
        String value=Combo_Day.getSelectedItem().toString();
        if(value.equals("Day1")){
            Update_table_sort(1);
        }
        else if(value.equals("Day2")){
            Update_table_sort(2);
        }
        else if(value.equals("Day3")){
            Update_table_sort(3);
        } else {
        }
    }//GEN-LAST:event_Combo_sortItemStateChanged

    private void event_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_event_tableMouseClicked
        // TODO add your handling code here:
        try{
            String value=Combo_Day.getSelectedItem().toString();
            int row = event_table.getSelectedRow();
            String Table_click=(event_table.getModel().getValueAt(row, 0).toString());
            String sql="select * from "+value+"events where Eventid='"+Table_click+"'";
            pst= conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                text_id.setText(rs.getString("Eventid"));
                text_name.setText(rs.getString("Eventname"));
                text_time.setText(rs.getString("Starttime"));
                text_etime.setText(rs.getString("Endtime"));
                text_venue.setText(rs.getString("Venue"));
                text_seats.setText(rs.getString("Seats"));
                text_desc.setText(rs.getString("Description"));
                asas.setText(rs.getString("Availableseats"));
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
        try{
            rs.close();
            pst.close();
        }
        catch(Exception e){
            
        }
    }
        
    }//GEN-LAST:event_event_tableMouseClicked

    private void text_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_descActionPerformed
    public void cclose(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        cclose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eventsdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eventsdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eventsdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eventsdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eventsdetails().setVisible(true);
            }
        });
    }
    private void show_times(){
        Thread clock=new Thread(){
            public void run(){
                for(;;){
                        Calendar c=new GregorianCalendar();
                        int month=c.get(Calendar.MONTH);
                        int year=c.get(Calendar.YEAR);
                        int day=c.get(Calendar.DAY_OF_MONTH);
                        datess.setText("DATE:"+day+"/"+(month+1)+"/"+year);
                        int second=c.get(Calendar.SECOND);
                        int minute=c.get(Calendar.MINUTE);
                        int hour=c.get(Calendar.HOUR);
                        timess.setText("TIME:"+hour+":"+minute+":"+second);

                    try{
                        sleep(1000);
                    }catch(InterruptedException e){
                        JOptionPane.showMessageDialog(null,"TimEEE ErroRRR!!");

                    }
                }
            }
        };
        clock.start();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combo_Day;
    private javax.swing.JComboBox<String> Combo_sort;
    private javax.swing.JTextField asas;
    private javax.swing.JMenu datess;
    private javax.swing.JTable event_table;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField text_desc;
    private javax.swing.JTextField text_etime;
    private javax.swing.JTextField text_id;
    private javax.swing.JTextField text_name;
    private javax.swing.JTextField text_seats;
    private javax.swing.JTextField text_time;
    private javax.swing.JTextField text_venue;
    private javax.swing.JMenu timess;
    // End of variables declaration//GEN-END:variables
}
