
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vaibhav
 */
public class Moneyapproval extends javax.swing.JFrame {
    Connection conn=null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form Moneyapproval
     */
    public Moneyapproval() {
        initComponents();
        conn=javaconnect.ConnecrDb();
        Update_table();
    }
     private void Update_table(){
        String sql="select Username,Name,Moneydemand from Logindata where Moneydemand>0";
        try{
            pst= conn.prepareStatement(sql);
            rs=pst.executeQuery();
            money_table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
        try{
            rs.close();
            pst.close();
//            JOptionPane.showMessageDialog(null,"Closed");
        }
        catch(SQLException | HeadlessException e){
            
        }
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pp_uid = new javax.swing.JTextField();
        pp_mobile = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pp_institute = new javax.swing.JTextField();
        pp_city = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pp_address = new javax.swing.JTextField();
        pp_email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pp_moneydemand = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        pp_name = new javax.swing.JTextField();
        pp_state = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        money_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Approval Forum", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Utopia", 3, 36), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(254, 191, 127));
        jLabel3.setFont(new java.awt.Font("Utopia", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 82, 138));
        jLabel3.setText("Address");

        pp_uid.setFont(new java.awt.Font("Utopia", 0, 18)); // NOI18N
        pp_uid.setForeground(new java.awt.Color(223, 111, 24));

        pp_mobile.setEditable(false);
        pp_mobile.setFont(new java.awt.Font("Utopia", 0, 18)); // NOI18N
        pp_mobile.setForeground(new java.awt.Color(223, 111, 24));
        pp_mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp_mobileActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(254, 191, 127));
        jLabel5.setFont(new java.awt.Font("Utopia", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(2, 82, 138));
        jLabel5.setText("State");

        jLabel6.setBackground(new java.awt.Color(254, 191, 127));
        jLabel6.setFont(new java.awt.Font("Utopia", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(2, 82, 138));
        jLabel6.setText("Mobile No.");

        pp_institute.setEditable(false);
        pp_institute.setFont(new java.awt.Font("Utopia", 0, 18)); // NOI18N
        pp_institute.setForeground(new java.awt.Color(223, 111, 24));

        pp_city.setEditable(false);
        pp_city.setFont(new java.awt.Font("Utopia", 0, 18)); // NOI18N
        pp_city.setForeground(new java.awt.Color(223, 111, 24));

        jLabel1.setBackground(new java.awt.Color(254, 191, 127));
        jLabel1.setFont(new java.awt.Font("Utopia", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 82, 138));
        jLabel1.setText("Money Demanded");

        jButton1.setBackground(new java.awt.Color(147, 249, 240));
        jButton1.setFont(new java.awt.Font("Utopia", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(6, 2, 163));
        jButton1.setText("Approve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(254, 191, 127));
        jLabel4.setFont(new java.awt.Font("Utopia", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 82, 138));
        jLabel4.setText("City");

        jLabel8.setBackground(new java.awt.Color(254, 191, 127));
        jLabel8.setFont(new java.awt.Font("Utopia", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(2, 82, 138));
        jLabel8.setText("UserID");

        pp_address.setEditable(false);
        pp_address.setFont(new java.awt.Font("Utopia", 0, 18)); // NOI18N
        pp_address.setForeground(new java.awt.Color(223, 111, 24));

        pp_email.setEditable(false);
        pp_email.setFont(new java.awt.Font("Utopia", 0, 18)); // NOI18N
        pp_email.setForeground(new java.awt.Color(223, 111, 24));

        jLabel7.setBackground(new java.awt.Color(254, 191, 127));
        jLabel7.setFont(new java.awt.Font("Utopia", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(2, 82, 138));
        jLabel7.setText("E-Mail");

        pp_moneydemand.setFont(new java.awt.Font("Utopia", 0, 18)); // NOI18N
        pp_moneydemand.setForeground(new java.awt.Color(223, 111, 24));

        jLabel14.setBackground(new java.awt.Color(254, 191, 127));
        jLabel14.setFont(new java.awt.Font("Utopia", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(2, 82, 138));
        jLabel14.setText("Institute Name");

        pp_name.setEditable(false);
        pp_name.setFont(new java.awt.Font("Utopia", 0, 18)); // NOI18N
        pp_name.setForeground(new java.awt.Color(223, 111, 24));

        pp_state.setEditable(false);
        pp_state.setFont(new java.awt.Font("Utopia", 0, 18)); // NOI18N
        pp_state.setForeground(new java.awt.Color(223, 111, 24));
        pp_state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp_stateActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(254, 191, 127));
        jLabel2.setFont(new java.awt.Font("Utopia", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 82, 138));
        jLabel2.setText("Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(pp_moneydemand)
                    .addComponent(pp_institute)
                    .addComponent(pp_email)
                    .addComponent(pp_mobile)
                    .addComponent(pp_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(pp_address, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pp_city, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pp_state, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pp_uid))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(pp_uid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(pp_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pp_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pp_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pp_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(pp_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pp_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pp_institute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pp_moneydemand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Utopia", 3, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(253, 105, 18));
        jLabel9.setText("MONEY APPROVAL");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Users who requested for money", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Utopia", 3, 24), new java.awt.Color(15, 121, 22))); // NOI18N

        money_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        money_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                money_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(money_table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(354, 354, 354))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );

        setSize(new java.awt.Dimension(1056, 597));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pp_mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pp_mobileActionPerformed

    private void pp_stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp_stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pp_stateActionPerformed

    private void money_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_money_tableMouseClicked
        // TODO add your handling code here:
        try{
//            String value=Combo_Day.getSelectedItem().toString();
            int row = money_table.getSelectedRow();
            String Table_click=(money_table.getModel().getValueAt(row, 0).toString());
            String sql="select * from Logindata where Username='"+Table_click+"'";
            pst= conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                pp_uid.setText(rs.getString("Username"));
                pp_name.setText(rs.getString("Name"));
                pp_address.setText(rs.getString("Address"));
                pp_city.setText(rs.getString("City"));
                pp_state.setText(rs.getString("State"));
                pp_moneydemand.setText(rs.getString("Moneydemand"));
                pp_institute.setText(rs.getString("InstituteName"));
                pp_email.setText(rs.getString("Email"));
                pp_mobile.setText(rs.getString("Phoneno"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
        try{
            rs.close();
            pst.close();
        }
        catch(Exception e){
            
        }
    }
    }//GEN-LAST:event_money_tableMouseClicked
private void update(int wm,String user) throws SQLException{
    
        rs.close();
        pst.close();
        String Username=user;
        String Password=null;
        String Name=null;
        String Address=null;
        String Email=null;
        String Phoneno=null;
        String Activestatus=null;
        String Designation=null;
        String Institute=null;
        String City=null;
        String State=null;
        String Hall=null;
        String RoomNo=null;
        String Notifications=null;
        try{
            String sql="select * from Logindata where Username = ?";
            pst= conn.prepareStatement(sql);
            pst.setString(1,Username);
            rs=pst.executeQuery();
            if(rs.next()){
                Password=rs.getString("Password");
                Name=rs.getString("Name");
                Address=rs.getString("Address");
                Email=rs.getString("Email");
                Phoneno=rs.getString("Phoneno");
                Activestatus=rs.getString("Activestatus");
                Designation=rs.getString("Designation");
                Institute=rs.getString("InstituteName");
                City=rs.getString("City");
                State=rs.getString("State");
                Hall=rs.getString("HallName");
                RoomNo=rs.getString("RoomNo");
                Notifications=rs.getString("Notifications");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
        try{
                String sql="delete from Logindata where Username=?";
                pst= conn.prepareStatement(sql);
                pst.setString(1, Username);
                pst.execute();
                pst.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);            
            }
        }
//to change        
        try{
            String sql="Insert into Logindata (Username,Password,Name,Address,Email,Phoneno,Waletmoney,Activestatus,Designation,InstituteName,City,State,Moneydemand,HallName,RoomNo,Notifications) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pst= conn.prepareStatement(sql);
            pst.setString(1, Username);
            pst.setString(2, Password);
            pst.setString(3, Name);
            pst.setString(4, Address);
            pst.setString(5, Email);
            pst.setString(6, Phoneno);
            pst.setString(7, Integer.toString(wm));
            pst.setString(8, Activestatus);
            pst.setString(9, Designation);
            pst.setString(10, Institute);
            pst.setString(11, City);
            pst.setString(12, State);
            pst.setString(13, "0");
            pst.setString(14, Hall);
            pst.setString(15, RoomNo);
            pst.setString(16, Notifications);
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null,"APPROVED!!");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);            
            }
        }
}        
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
        String id= pp_uid.getText();
        String sql="select * from Logindata where Username=?";
        pst= conn.prepareStatement(sql);
        pst.setString(1, id);    
        rs=pst.executeQuery();
        if(rs.next()){
                String WM=rs.getString("Waletmoney");
                String MD=rs.getString("Moneydemand");
                int wm=Integer.parseInt(WM);
                int md=Integer.parseInt(MD);
                wm=wm+md;
//                JOptionPane.showMessageDialog(null,wm);               
                rs.close();
                pst.close();
                update(wm,id);
                Update_table();
                pp_uid.setText("");
                pp_name.setText("");
                pp_address.setText("");
                pp_city.setText("");
                pp_state.setText("");
                pp_institute.setText("");
                pp_mobile.setText("");
                pp_email.setText("");
                pp_moneydemand.setText("");                
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    catch(SQLException | NumberFormatException | HeadlessException e){
        JOptionPane.showMessageDialog(null,"Roorr in th house");
    }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);            
            }
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Moneyapproval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Moneyapproval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Moneyapproval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Moneyapproval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Moneyapproval().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable money_table;
    private javax.swing.JTextField pp_address;
    private javax.swing.JTextField pp_city;
    private javax.swing.JTextField pp_email;
    private javax.swing.JTextField pp_institute;
    private javax.swing.JTextField pp_mobile;
    private javax.swing.JTextField pp_moneydemand;
    private javax.swing.JTextField pp_name;
    private javax.swing.JTextField pp_state;
    private javax.swing.JTextField pp_uid;
    // End of variables declaration//GEN-END:variables
}
